### ISSUE TITLE
Request: offer samples of using Vulkan, migrated from Renderscript of the old live wallpapers

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/renderscript-samples#14]
In the past, we had some live wallpapers by Google, made using Renderscript.
Renderscript was put aside after some time, not being used for such purposes.
Now as I've noticed Vulkan should replace them:
https://android-developers.googleblog.com/2021/04/android-gpu-compute-going-forward.html

And here we got a sample of this migration, according to the same blog.

Can you please provide samples of using it on the same live wallpapers apps we used to have?

I think one of them looked like this:
https://youtu.be/K0i4PAXXBdQ?t=24

**Comment by Kottsone** [comment]
Thanks for your interest in the samples. Currently we do not have plan to add more samples in this repository. If you are referring to the Muzei live wallpaper app, please open an issue in https://github.com/muzei/muzei.

**Comment by AndroidDeveloperLB** [comment]
@Kottsone Please watch the video. It's not Muzei.
It's a spinning galaxy animation
And there were others too:
https://www.youtube.com/watch?v=Hz1YBcYw_qE

**Comment by Kottsone** [comment]
@AndroidDeveloperLB  Sorry for making the bad suggestion. I am not familiar with either Muzei or any of the app shown in the videos. 

I asked about the live wallpaper you mentioned, and it seems to be related to the graphics subsystem of RenderScript. This feature has been deprecated a long time ago, so it is not relevant to the recent deprecation. It's probably a good idea to request such a sample in the [NDK samples repository](https://github.com/android/ndk-samples) or the [Vulkan samples repository](https://github.com/googlesamples/vulkan-basic-samples).

**Comment by AndroidDeveloperLB** [comment]
@Kottsone OK here:
https://github.com/googlesamples/vulkan-basic-samples/issues/36

Hopefully they will accept some ideas.
