### ISSUE TITLE
RenderEffect Code

### ISSUE THREAD

**Issue by dburckh** [android/renderscript-samples#19]
I've written an ImageProcessor that uses the new RenderEffect code from Android S.  I would like to contribute it.  Please allow me create a branch and a PR.  I have already agreed to the Google CLA.

**Comment by Kottsone** [comment]
Hi @dburckh, thanks for your interest in the samples. Contributions are welcome!

To contribute code to this repository, please simply fork the repo and create a PR from there. You can find more information [here](https://docs.github.com/en/get-started/quickstart/contributing-to-projects).

**Comment by dburckh** [comment]
Not sure if it popped up, but I did the PR a few days ago.  Let me know if there are any issues or questions.

**Comment by Kottsone** [comment]
PR is approved and merged. Closing this issue.
