### ISSUE TITLE
How to choose workgroup size

### ISSUE THREAD

**Issue by GainLee** [android/renderscript-samples#22]
I notice that code "// We prefer the workgroup size to be a multiple of 4." , why should we do this?

**Comment by Kottsone** [comment]
The logic there is somewhat naive. Usually, it is a good idea to make the total workgroup size being a multiple of the subgroup size (see https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceSubgroupProperties.html), and most mobile GPU drivers report a >= 16 subgroup size. For simplicity, the sample implementation uses a square workgroup, so for each dimension, a multiple of 4 is preferred.

**Comment by GainLee** [comment]
:)
